//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allotments_LevelTypes
    {
        public Allotments_LevelTypes()
        {
            this.Allotments_SalaryLevels = new HashSet<Allotments_SalaryLevels>();
        }
    
        public int LevelTypeId { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<Allotments_SalaryLevels> Allotments_SalaryLevels { get; set; }
    }
}
