//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allotments_StaffSchedule
    {
        public int ScheduleId { get; set; }
        public int TeacherSalaryId { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> FinishTime { get; set; }
        public System.DateTime RecCreatedDt { get; set; }
        public string RecCreatedBy { get; set; }
        public System.DateTime RecLastUpdateDate { get; set; }
        public string RecLastUpdatedBy { get; set; }
        public int DayId { get; set; }
        public Nullable<int> CampusId { get; set; }
        public int Year { get; set; }
    
        public virtual Allotments_TeacherSalaries Allotments_TeacherSalaries { get; set; }
    }
}
