//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allotments_TeacherResponsibilities
    {
        public int TeacherResponsibilityId { get; set; }
        public int TeacherSalaryId { get; set; }
        public int SalaryLevelId { get; set; }
        public string Description { get; set; }
    
        public virtual Allotments_SalaryLevels Allotments_SalaryLevels { get; set; }
        public virtual Allotments_TeacherSalaries Allotments_TeacherSalaries { get; set; }
    }
}
