//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATT_Schedule
    {
        public ATT_Schedule()
        {
            this.Att_Staff_AdvanceReplacements = new HashSet<Att_Staff_AdvanceReplacements>();
            this.Att_Staff_ExemptedPeriods = new HashSet<Att_Staff_ExemptedPeriods>();
            this.Att_Staff_Replacements = new HashSet<Att_Staff_Replacements>();
        }
    
        public int ScheduleId { get; set; }
        public Nullable<int> PeriodId { get; set; }
        public int RoomId { get; set; }
        public Nullable<int> TeacherClassCodeId { get; set; }
        public Nullable<int> ScheduleCycleId { get; set; }
        public string WeekDay { get; set; }
        public Nullable<System.DateTime> ScheduleStartDate { get; set; }
        public byte DayInWeek { get; set; }
    
        public virtual Config_Period Config_Period { get; set; }
        public virtual TeacherClassCode TeacherClassCode { get; set; }
        public virtual ICollection<Att_Staff_AdvanceReplacements> Att_Staff_AdvanceReplacements { get; set; }
        public virtual ICollection<Att_Staff_ExemptedPeriods> Att_Staff_ExemptedPeriods { get; set; }
        public virtual ICollection<Att_Staff_Replacements> Att_Staff_Replacements { get; set; }
    }
}
