//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Att_Staff_HomeroomReplacements
    {
        public int ReplacementId { get; set; }
        public int ClassTeacherId { get; set; }
        public int ReplacingTeacherId { get; set; }
        public System.DateTime RecCreatedDate { get; set; }
        public System.DateTime RecLastUpdatedDate { get; set; }
        public bool PeriodType { get; set; }
    
        public virtual TR_ClassTeachers TR_ClassTeachers { get; set; }
        public virtual TR_Teachers TR_Teachers { get; set; }
    }
}
