//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATT_LatePass
    {
        public int LatePassId { get; set; }
        public Nullable<int> AttendanceStatusId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> StudentAttendanceId { get; set; }
        public Nullable<System.DateTime> LatePassDate { get; set; }
        public Nullable<System.DateTime> LatePassTime { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
    }
}
