//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATT_Student_Attendance
    {
        public int StudentAttendanceId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> AttendanceStatusId { get; set; }
        public Nullable<int> RollTimeStatusId { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> AttendanceDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Reason { get; set; }
        public string ReasonTitle { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED_DATE { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<int> LAST_MODIFIED_BY { get; set; }
        public Nullable<int> VERSION_NUMBER { get; set; }
        public Nullable<int> StudentClassCodeId { get; set; }
        public Nullable<int> PeriodId { get; set; }
    }
}
