//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Att_Staff_InServiceRequests
    {
        public int InServiceRequestId { get; set; }
        public int InServiceRequestTypeId { get; set; }
        public int TeacherId { get; set; }
        public short StatusId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public string Description { get; set; }
        public System.DateTime RecCreatedDate { get; set; }
        public int RecCreatedBy { get; set; }
        public System.DateTime RecLastUpdatedDate { get; set; }
        public int RecLastUpdatedBy { get; set; }
        public Nullable<int> DayOption { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int StatusLevelId { get; set; }
        public string Venue { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string Provider { get; set; }
        public string Response { get; set; }
        public string Domain { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public int CampusId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<bool> DomainBudgetRequired { get; set; }
    
        public virtual Config_Statuses Config_Statuses { get; set; }
        public virtual TR_Teachers TR_Teachers { get; set; }
    }
}
