//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Att_Staff_Leaves
    {
        public Att_Staff_Leaves()
        {
            this.TR_LeaveLog = new HashSet<TR_LeaveLog>();
        }
    
        public int LeaveId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Reason { get; set; }
        public short StatusId { get; set; }
        public int DayOptionId { get; set; }
        public Nullable<bool> IsArchieved { get; set; }
        public Nullable<int> LeaveTypeId { get; set; }
        public int TeacherId { get; set; }
        public System.DateTime RecCreatedDt { get; set; }
        public System.DateTime RecLastUpdatedDt { get; set; }
        public Nullable<int> RecCreatedBy { get; set; }
        public Nullable<int> RecUpdatedBy { get; set; }
        public bool isDeleted { get; set; }
        public string Attachment { get; set; }
    
        public virtual LeaveType LeaveType { get; set; }
        public virtual TR_Teachers TR_Teachers { get; set; }
        public virtual ICollection<TR_LeaveLog> TR_LeaveLog { get; set; }
    }
}
