//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATT_EvacuationAttendance
    {
        public int EvacuationAttendanceId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> AttendanceStatusId { get; set; }
        public Nullable<int> RollTimeStatusId { get; set; }
        public Nullable<System.DateTime> AttendanceDate { get; set; }
        public Nullable<int> StudentClassId { get; set; }
        public Nullable<int> SectionId { get; set; }
        public Nullable<int> TermId { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED_DATE { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<int> LAST_MODIFIED_BY { get; set; }
        public Nullable<int> VERSION_NUMBER { get; set; }
    }
}
