//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CH_BalanceEmailLogs
    {
        public int EmailLogId { get; set; }
        public int DomainBalanceId { get; set; }
        public int TeacherId { get; set; }
        public int UsageRangeId { get; set; }
        public System.DateTime RecCreatedDate { get; set; }
    
        public virtual Config_BalanceUsageRange Config_BalanceUsageRange { get; set; }
    }
}
