//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CH_ClassCoordinatorMapping
    {
        public int ClassCoordinatorMappingId { get; set; }
        public int TeacherId { get; set; }
        public int ClassId { get; set; }
        public int SubjectId { get; set; }
        public int TermId { get; set; }
        public int CampusId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> SendEmail { get; set; }
    }
}
