//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeLog_DomainBalance
    {
        public int ChangeLogId { get; set; }
        public int SubjectId { get; set; }
        public decimal BalanceBefore { get; set; }
        public decimal BalanceAfter { get; set; }
        public int ChangedBy { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public int CampusId { get; set; }
        public Nullable<int> ClassLevelId { get; set; }
        public short ChangeType { get; set; }
        public Nullable<int> ChainId { get; set; }
        public string Comments { get; set; }
    }
}
