//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassCode
    {
        public ClassCode()
        {
            this.Config_SubjectWorkHabits = new HashSet<Config_SubjectWorkHabits>();
            this.TaskAssessments = new HashSet<TaskAssessment>();
            this.TeacherClassCodes = new HashSet<TeacherClassCode>();
        }
    
        public int ClassCodeId { get; set; }
        public int ClassId { get; set; }
        public int SubjectId { get; set; }
        public string Code { get; set; }
        public string ClassStream { get; set; }
        public Nullable<int> CampusId { get; set; }
    
        public virtual ICollection<Config_SubjectWorkHabits> Config_SubjectWorkHabits { get; set; }
        public virtual Config_Class Config_Class { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual ICollection<TaskAssessment> TaskAssessments { get; set; }
        public virtual ICollection<TeacherClassCode> TeacherClassCodes { get; set; }
    }
}
