//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config_Terms
    {
        public Config_Terms()
        {
            this.AssessmentLinks = new HashSet<AssessmentLink>();
            this.Config_Leadership_Team = new HashSet<Config_Leadership_Team>();
            this.TeacherClassCodes = new HashSet<TeacherClassCode>();
            this.TermWeights = new HashSet<TermWeight>();
        }
    
        public int TermId { get; set; }
        public string TermNo { get; set; }
        public string TermYear { get; set; }
        public Nullable<System.DateTime> StartingDate { get; set; }
        public Nullable<System.DateTime> EndingDate { get; set; }
        public string TermDescription { get; set; }
        public Nullable<int> CampusId { get; set; }
        public Nullable<int> SemesterId { get; set; }
        public Nullable<System.DateTime> ReportsDate { get; set; }
    
        public virtual ICollection<AssessmentLink> AssessmentLinks { get; set; }
        public virtual ICollection<Config_Leadership_Team> Config_Leadership_Team { get; set; }
        public virtual Semester Semester { get; set; }
        public virtual ICollection<TeacherClassCode> TeacherClassCodes { get; set; }
        public virtual ICollection<TermWeight> TermWeights { get; set; }
    }
}
