//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config_StaffCategory
    {
        public Config_StaffCategory()
        {
            this.TR_EmploymentHistory = new HashSet<TR_EmploymentHistory>();
            this.TR_RequestRights = new HashSet<TR_RequestRights>();
        }
    
        public int CategoryId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<int> StaffCategoryType { get; set; }
    
        public virtual ICollection<TR_EmploymentHistory> TR_EmploymentHistory { get; set; }
        public virtual ICollection<TR_RequestRights> TR_RequestRights { get; set; }
    }
}
