//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config_StaffWorkLoad
    {
        public Config_StaffWorkLoad()
        {
            this.Allotments_TeacherSalaries = new HashSet<Allotments_TeacherSalaries>();
            this.TR_EmploymentHistory = new HashSet<TR_EmploymentHistory>();
        }
    
        public int WorkLoadId { get; set; }
        public decimal LoadType { get; set; }
    
        public virtual ICollection<Allotments_TeacherSalaries> Allotments_TeacherSalaries { get; set; }
        public virtual ICollection<TR_EmploymentHistory> TR_EmploymentHistory { get; set; }
    }
}
