//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config_InjuryTypes
    {
        public int InjuryTypeId { get; set; }
        public string Name { get; set; }
        public int TypeKey { get; set; }
        public Nullable<bool> ShowInForms { get; set; }
    }
}
