//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config_Task
    {
        public Config_Task()
        {
            this.TaskAssessments = new HashSet<TaskAssessment>();
        }
    
        public int TaskTypeId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<int> ClassId { get; set; }
    
        public virtual Subject Subject { get; set; }
        public virtual ICollection<TaskAssessment> TaskAssessments { get; set; }
    }
}
