//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config_AfterSchoolReflectionSchedule
    {
        public int AfterSchoolReflectionScheduleId { get; set; }
        public int CampusId { get; set; }
        public int ClassLevelId { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan FinishTime { get; set; }
        public int Day { get; set; }
        public int HoursBeforeNotify { get; set; }
        public string MessageBody { get; set; }
        public short SuspensionStatusId { get; set; }
    
        public virtual Config_Campus Config_Campus { get; set; }
        public virtual Config_Statuses Config_Statuses { get; set; }
    }
}
