//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config_Class
    {
        public Config_Class()
        {
            this.AssessmentLinks = new HashSet<AssessmentLink>();
            this.CH_DomainHeadMapping = new HashSet<CH_DomainHeadMapping>();
            this.ClassCodes = new HashSet<ClassCode>();
            this.Config_Leadership_Team = new HashSet<Config_Leadership_Team>();
            this.Msg_TeacherAssociation = new HashSet<Msg_TeacherAssociation>();
            this.SR_Student_Classes = new HashSet<SR_Student_Classes>();
            this.TR_ClassTeachers = new HashSet<TR_ClassTeachers>();
            this.TR_IncursionExcursionClasses = new HashSet<TR_IncursionExcursionClasses>();
            this.TR_TeacherVenueHireRequestClassses = new HashSet<TR_TeacherVenueHireRequestClassses>();
        }
    
        public int ClassId { get; set; }
        public string Name { get; set; }
        public Nullable<int> ClassOrder { get; set; }
        public Nullable<int> ClassLevelId { get; set; }
    
        public virtual ICollection<AssessmentLink> AssessmentLinks { get; set; }
        public virtual ICollection<CH_DomainHeadMapping> CH_DomainHeadMapping { get; set; }
        public virtual ICollection<ClassCode> ClassCodes { get; set; }
        public virtual ICollection<Config_Leadership_Team> Config_Leadership_Team { get; set; }
        public virtual ICollection<Msg_TeacherAssociation> Msg_TeacherAssociation { get; set; }
        public virtual ICollection<SR_Student_Classes> SR_Student_Classes { get; set; }
        public virtual ICollection<TR_ClassTeachers> TR_ClassTeachers { get; set; }
        public virtual ICollection<TR_IncursionExcursionClasses> TR_IncursionExcursionClasses { get; set; }
        public virtual ICollection<TR_TeacherVenueHireRequestClassses> TR_TeacherVenueHireRequestClassses { get; set; }
    }
}
