//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config_GradeScales
    {
        public int GradeScaleId { get; set; }
        public string Grade { get; set; }
        public string Scale { get; set; }
        public int CampusId { get; set; }
        public int ClassLevelId { get; set; }
        public string Year { get; set; }
        public int CssType { get; set; }
        public int SortOrder { get; set; }
        public string Description { get; set; }
    
        public virtual Config_Campus Config_Campus { get; set; }
    }
}
