//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config_Campus
    {
        public Config_Campus()
        {
            this.Allotments_TeacherSalaries = new HashSet<Allotments_TeacherSalaries>();
            this.ATT_Staff_Attendance = new HashSet<ATT_Staff_Attendance>();
            this.Config_AfterSchoolReflectionSchedule = new HashSet<Config_AfterSchoolReflectionSchedule>();
            this.SR_Students = new HashSet<SR_Students>();
            this.Config_VenueHire_Types = new HashSet<Config_VenueHire_Types>();
            this.Config_GradeScales = new HashSet<Config_GradeScales>();
            this.Config_Leadership_Team = new HashSet<Config_Leadership_Team>();
            this.Config_DomainBalance = new HashSet<Config_DomainBalance>();
            this.Msg_TeacherAssociation = new HashSet<Msg_TeacherAssociation>();
            this.TR_EmploymentHistory = new HashSet<TR_EmploymentHistory>();
            this.TR_HazardRequests = new HashSet<TR_HazardRequests>();
            this.TR_ItSupportRequests = new HashSet<TR_ItSupportRequests>();
            this.TR_MaintenanceRequests = new HashSet<TR_MaintenanceRequests>();
            this.TR_PurchaseOrderRequests = new HashSet<TR_PurchaseOrderRequests>();
            this.TR_RequestRights = new HashSet<TR_RequestRights>();
        }
    
        public int CampusId { get; set; }
        public string CampusName { get; set; }
        public string CampusCode { get; set; }
        public string Logo { get; set; }
        public string Address { get; set; }
        public string Subrub { get; set; }
        public string State { get; set; }
        public string PostCode { get; set; }
        public string ContactNo { get; set; }
        public string Email { get; set; }
        public string Timezone { get; set; }
        public string Fax { get; set; }
        public string Website { get; set; }
    
        public virtual ICollection<Allotments_TeacherSalaries> Allotments_TeacherSalaries { get; set; }
        public virtual ICollection<ATT_Staff_Attendance> ATT_Staff_Attendance { get; set; }
        public virtual ICollection<Config_AfterSchoolReflectionSchedule> Config_AfterSchoolReflectionSchedule { get; set; }
        public virtual ICollection<SR_Students> SR_Students { get; set; }
        public virtual ICollection<Config_VenueHire_Types> Config_VenueHire_Types { get; set; }
        public virtual ICollection<Config_GradeScales> Config_GradeScales { get; set; }
        public virtual ICollection<Config_Leadership_Team> Config_Leadership_Team { get; set; }
        public virtual ICollection<Config_DomainBalance> Config_DomainBalance { get; set; }
        public virtual ICollection<Msg_TeacherAssociation> Msg_TeacherAssociation { get; set; }
        public virtual ICollection<TR_EmploymentHistory> TR_EmploymentHistory { get; set; }
        public virtual ICollection<TR_HazardRequests> TR_HazardRequests { get; set; }
        public virtual ICollection<TR_ItSupportRequests> TR_ItSupportRequests { get; set; }
        public virtual ICollection<TR_MaintenanceRequests> TR_MaintenanceRequests { get; set; }
        public virtual ICollection<TR_PurchaseOrderRequests> TR_PurchaseOrderRequests { get; set; }
        public virtual ICollection<TR_RequestRights> TR_RequestRights { get; set; }
    }
}
