//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config_HazardTypes
    {
        public Config_HazardTypes()
        {
            this.TR_HazardRequests = new HashSet<TR_HazardRequests>();
        }
    
        public int HazardTypeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int HazardTypeKey { get; set; }
    
        public virtual ICollection<TR_HazardRequests> TR_HazardRequests { get; set; }
    }
}
