//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config_BalanceUsageRange
    {
        public Config_BalanceUsageRange()
        {
            this.CH_BalanceEmailLogs = new HashSet<CH_BalanceEmailLogs>();
        }
    
        public int UsageRangeId { get; set; }
        public decimal StartValue { get; set; }
        public decimal EndValue { get; set; }
        public int UsageRangeKey { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<CH_BalanceEmailLogs> CH_BalanceEmailLogs { get; set; }
    }
}
