//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config_AddressType
    {
        public Config_AddressType()
        {
            this.ST_AddressInformation = new HashSet<ST_AddressInformation>();
        }
    
        public int AddressTypeId { get; set; }
        public string Name { get; set; }
        public int AddressTypeKey { get; set; }
    
        public virtual ICollection<ST_AddressInformation> ST_AddressInformation { get; set; }
    }
}
