//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config_VaccinationTypes
    {
        public Config_VaccinationTypes()
        {
            this.StudentVaccinationHistories = new HashSet<StudentVaccinationHistory>();
        }
    
        public int VaccinationTypeId { get; set; }
        public string Name { get; set; }
        public int TypeKey { get; set; }
    
        public virtual ICollection<StudentVaccinationHistory> StudentVaccinationHistories { get; set; }
    }
}
