//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config_RequestTypes
    {
        public Config_RequestTypes()
        {
            this.TR_RequestRights = new HashSet<TR_RequestRights>();
            this.Config_Statuses = new HashSet<Config_Statuses>();
        }
    
        public short RequestTypeId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public short RequestKey { get; set; }
    
        public virtual ICollection<TR_RequestRights> TR_RequestRights { get; set; }
        public virtual ICollection<Config_Statuses> Config_Statuses { get; set; }
    }
}
