//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config_MedicalCardTypes
    {
        public Config_MedicalCardTypes()
        {
            this.SR_Student_MedicalCards = new HashSet<SR_Student_MedicalCards>();
        }
    
        public int MedicalCardTypeId { get; set; }
        public string Name { get; set; }
        public int TypeKey { get; set; }
    
        public virtual ICollection<SR_Student_MedicalCards> SR_Student_MedicalCards { get; set; }
    }
}
