//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config_StaffBreak
    {
        public Config_StaffBreak()
        {
            this.TR_StaffSchedule = new HashSet<TR_StaffSchedule>();
        }
    
        public int BreakId { get; set; }
        public string BreakTime { get; set; }
    
        public virtual ICollection<TR_StaffSchedule> TR_StaffSchedule { get; set; }
    }
}
