//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config_Room
    {
        public Config_Room()
        {
            this.SR_Student_SchoolMedicalHistory = new HashSet<SR_Student_SchoolMedicalHistory>();
            this.SR_Student_SchoolMedicalHistory1 = new HashSet<SR_Student_SchoolMedicalHistory>();
        }
    
        public int RoomId { get; set; }
        public string RoomName { get; set; }
        public Nullable<int> CampusId { get; set; }
    
        public virtual ICollection<SR_Student_SchoolMedicalHistory> SR_Student_SchoolMedicalHistory { get; set; }
        public virtual ICollection<SR_Student_SchoolMedicalHistory> SR_Student_SchoolMedicalHistory1 { get; set; }
    }
}
