//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config_StudentWorkHabit
    {
        public int StudentWorkHabitId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> WorkHabitId { get; set; }
        public Nullable<int> WorkHabitValueId { get; set; }
        public Nullable<int> TeacherId { get; set; }
        public Nullable<int> TermId { get; set; }
    
        public virtual Config_WorkHabits Config_WorkHabits { get; set; }
        public virtual Config_WorkHabitValues Config_WorkHabitValues { get; set; }
        public virtual SR_Students SR_Students { get; set; }
        public virtual TR_Teachers TR_Teachers { get; set; }
    }
}
