//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config_Section
    {
        public Config_Section()
        {
            this.SR_Student_Classes = new HashSet<SR_Student_Classes>();
            this.TR_ClassTeachers = new HashSet<TR_ClassTeachers>();
            this.TR_IncursionExcursionClasses = new HashSet<TR_IncursionExcursionClasses>();
            this.TR_TeacherVenueHireRequestClassses = new HashSet<TR_TeacherVenueHireRequestClassses>();
        }
    
        public int SectionId { get; set; }
        public string Name { get; set; }
        public Nullable<int> SectionOrder { get; set; }
        public Nullable<int> DisplayNumber { get; set; }
    
        public virtual ICollection<SR_Student_Classes> SR_Student_Classes { get; set; }
        public virtual ICollection<TR_ClassTeachers> TR_ClassTeachers { get; set; }
        public virtual ICollection<TR_IncursionExcursionClasses> TR_IncursionExcursionClasses { get; set; }
        public virtual ICollection<TR_TeacherVenueHireRequestClassses> TR_TeacherVenueHireRequestClassses { get; set; }
    }
}
