//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config_MedicalConditionTypes
    {
        public Config_MedicalConditionTypes()
        {
            this.SR_Student_MedicalConditions = new HashSet<SR_Student_MedicalConditions>();
        }
    
        public int MedicalConditionTypeId { get; set; }
        public string Name { get; set; }
        public int TypeKey { get; set; }
    
        public virtual ICollection<SR_Student_MedicalConditions> SR_Student_MedicalConditions { get; set; }
    }
}
