//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config_WeightThresholds
    {
        public int ThresholdId { get; set; }
        public int ClassLevelId { get; set; }
        public int CampusId { get; set; }
        public int ThresholdWeight { get; set; }
    }
}
