//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config_DomainBalance
    {
        public int DomainBalanceId { get; set; }
        public int SubjectId { get; set; }
        public decimal Balance { get; set; }
        public string BalanceYear { get; set; }
        public int CampusId { get; set; }
        public Nullable<int> ClassLevelId { get; set; }
        public Nullable<decimal> InitialBudget { get; set; }
    
        public virtual Config_Campus Config_Campus { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
