//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config_MaintenanceTypes
    {
        public Config_MaintenanceTypes()
        {
            this.TR_MaintenanceRequests = new HashSet<TR_MaintenanceRequests>();
        }
    
        public int MaintenanceTypeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int MaintenanceTypeKey { get; set; }
    
        public virtual ICollection<TR_MaintenanceRequests> TR_MaintenanceRequests { get; set; }
    }
}
