//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config_BehaviorLevels
    {
        public short BehaviorLevelId { get; set; }
        public string Name { get; set; }
        public int StartingRange { get; set; }
        public int EndingRange { get; set; }
        public short LevelKey { get; set; }
        public int CampusId { get; set; }
        public int ClassLevelId { get; set; }
    }
}
