//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StaffAttendanceEntities : DbContext
    {
        public StaffAttendanceEntities()
            : base("name=StaffAttendanceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public DbSet<Allotments_LevelTypes> Allotments_LevelTypes { get; set; }
        public DbSet<Allotments_SalaryLevels> Allotments_SalaryLevels { get; set; }
        public DbSet<Allotments_StaffSchedule> Allotments_StaffSchedule { get; set; }
        public DbSet<Allotments_TeacherResponsibilities> Allotments_TeacherResponsibilities { get; set; }
        public DbSet<Allotments_TeacherSalaries> Allotments_TeacherSalaries { get; set; }
        public DbSet<AssessmentLink> AssessmentLinks { get; set; }
        public DbSet<ATT_Absent_Reasons> ATT_Absent_Reasons { get; set; }
        public DbSet<ATT_EvacuationAttendance> ATT_EvacuationAttendance { get; set; }
        public DbSet<ATT_LatePass> ATT_LatePass { get; set; }
        public DbSet<ATT_RollTime_Status> ATT_RollTime_Status { get; set; }
        public DbSet<ATT_Schedule> ATT_Schedule { get; set; }
        public DbSet<Att_Staff_AdvanceReplacements> Att_Staff_AdvanceReplacements { get; set; }
        public DbSet<ATT_Staff_Attendance> ATT_Staff_Attendance { get; set; }
        public DbSet<Att_Staff_ExemptedPeriods> Att_Staff_ExemptedPeriods { get; set; }
        public DbSet<Att_Staff_HomeroomReplacements> Att_Staff_HomeroomReplacements { get; set; }
        public DbSet<Att_Staff_InServiceRequests> Att_Staff_InServiceRequests { get; set; }
        public DbSet<Att_Staff_Leaves> Att_Staff_Leaves { get; set; }
        public DbSet<Att_Staff_Replacements> Att_Staff_Replacements { get; set; }
        public DbSet<ATT_Student_Attendance> ATT_Student_Attendance { get; set; }
        public DbSet<Att_StudentReflection_Attendance> Att_StudentReflection_Attendance { get; set; }
        public DbSet<CH_BalanceEmailLogs> CH_BalanceEmailLogs { get; set; }
        public DbSet<CH_Chronicle> CH_Chronicle { get; set; }
        public DbSet<CH_ClassCoordinatorMapping> CH_ClassCoordinatorMapping { get; set; }
        public DbSet<CH_DomainHeadMapping> CH_DomainHeadMapping { get; set; }
        public DbSet<ChangeLog_DomainBalance> ChangeLog_DomainBalance { get; set; }
        public DbSet<ClassCode> ClassCodes { get; set; }
        public DbSet<ClassScheduleCycle> ClassScheduleCycles { get; set; }
        public DbSet<Config_AddressType> Config_AddressType { get; set; }
        public DbSet<Config_AfterSchoolReflectionSchedule> Config_AfterSchoolReflectionSchedule { get; set; }
        public DbSet<Config_BalanceUsageRange> Config_BalanceUsageRange { get; set; }
        public DbSet<Config_BehaviorLevels> Config_BehaviorLevels { get; set; }
        public DbSet<Config_BehaviorTypes> Config_BehaviorTypes { get; set; }
        public DbSet<Config_CallerTypes> Config_CallerTypes { get; set; }
        public DbSet<Config_Campus> Config_Campus { get; set; }
        public DbSet<Config_Class> Config_Class { get; set; }
        public DbSet<Config_DomainBalance> Config_DomainBalance { get; set; }
        public DbSet<Config_FeedbackTypes> Config_FeedbackTypes { get; set; }
        public DbSet<Config_GradeScales> Config_GradeScales { get; set; }
        public DbSet<Config_GradesRange> Config_GradesRange { get; set; }
        public DbSet<Config_GuardianType> Config_GuardianType { get; set; }
        public DbSet<Config_HazardTypes> Config_HazardTypes { get; set; }
        public DbSet<Config_IncidentAction> Config_IncidentAction { get; set; }
        public DbSet<Config_IncidentType> Config_IncidentType { get; set; }
        public DbSet<Config_InjuryLocations> Config_InjuryLocations { get; set; }
        public DbSet<Config_InjuryTypes> Config_InjuryTypes { get; set; }
        public DbSet<Config_InServiceRequestType> Config_InServiceRequestType { get; set; }
        public DbSet<Config_ItSupportTypes> Config_ItSupportTypes { get; set; }
        public DbSet<Config_Leadership_Team> Config_Leadership_Team { get; set; }
        public DbSet<Config_MaintenanceTypes> Config_MaintenanceTypes { get; set; }
        public DbSet<Config_MedicalCardTypes> Config_MedicalCardTypes { get; set; }
        public DbSet<Config_MedicalConditionTypes> Config_MedicalConditionTypes { get; set; }
        public DbSet<Config_Period> Config_Period { get; set; }
        public DbSet<Config_RequestTypes> Config_RequestTypes { get; set; }
        public DbSet<Config_Room> Config_Room { get; set; }
        public DbSet<Config_ScheduleCycle> Config_ScheduleCycle { get; set; }
        public DbSet<Config_Section> Config_Section { get; set; }
        public DbSet<Config_StaffBreak> Config_StaffBreak { get; set; }
        public DbSet<Config_StaffCategory> Config_StaffCategory { get; set; }
        public DbSet<Config_StaffWorkDays> Config_StaffWorkDays { get; set; }
        public DbSet<Config_StaffWorkLoad> Config_StaffWorkLoad { get; set; }
        public DbSet<Config_Statuses> Config_Statuses { get; set; }
        public DbSet<Config_StatusLevel> Config_StatusLevel { get; set; }
        public DbSet<Config_StudentWorkHabit> Config_StudentWorkHabit { get; set; }
        public DbSet<Config_SubjectWorkHabits> Config_SubjectWorkHabits { get; set; }
        public DbSet<Config_Task> Config_Task { get; set; }
        public DbSet<Config_Terms> Config_Terms { get; set; }
        public DbSet<Config_VaccinationAgeTypes> Config_VaccinationAgeTypes { get; set; }
        public DbSet<Config_VaccinationTypes> Config_VaccinationTypes { get; set; }
        public DbSet<Config_VenueHire_Types> Config_VenueHire_Types { get; set; }
        public DbSet<Config_WeightThresholds> Config_WeightThresholds { get; set; }
        public DbSet<Config_WorkHabits> Config_WorkHabits { get; set; }
        public DbSet<Config_WorkHabitValues> Config_WorkHabitValues { get; set; }
        public DbSet<EmailRestriction> EmailRestrictions { get; set; }
        public DbSet<EmailTemplate> EmailTemplates { get; set; }
        public DbSet<EMP_ClassCoordinatorAssociation> EMP_ClassCoordinatorAssociation { get; set; }
        public DbSet<EvaluationType> EvaluationTypes { get; set; }
        public DbSet<Feedback> Feedbacks { get; set; }
        public DbSet<Feedback_Callers> Feedback_Callers { get; set; }
        public DbSet<Feedback_RelatedStaff> Feedback_RelatedStaff { get; set; }
        public DbSet<Grade> Grades { get; set; }
        public DbSet<LeaveType> LeaveTypes { get; set; }
        public DbSet<MedicalHistory> MedicalHistories { get; set; }
        public DbSet<MSG_MessageResponse> MSG_MessageResponse { get; set; }
        public DbSet<MSG_MessageStatus> MSG_MessageStatus { get; set; }
        public DbSet<Msg_TeacherAssociation> Msg_TeacherAssociation { get; set; }
        public DbSet<MSG_Template> MSG_Template { get; set; }
        public DbSet<Notification> Notifications { get; set; }
        public DbSet<Notification_Configuration> Notification_Configuration { get; set; }
        public DbSet<ParentPortalLog> ParentPortalLogs { get; set; }
        public DbSet<PreApprovedSubject> PreApprovedSubjects { get; set; }
        public DbSet<Role_AttendanceStatus> Role_AttendanceStatus { get; set; }
        public DbSet<Rpt_BehaviorReports> Rpt_BehaviorReports { get; set; }
        public DbSet<Rpt_BehaviorWitnesses> Rpt_BehaviorWitnesses { get; set; }
        public DbSet<Rpt_IncidentParties> Rpt_IncidentParties { get; set; }
        public DbSet<Rpt_Incidents> Rpt_Incidents { get; set; }
        public DbSet<Rpt_IncidentWitnesses> Rpt_IncidentWitnesses { get; set; }
        public DbSet<Semester> Semesters { get; set; }
        public DbSet<SR_Student_Balance> SR_Student_Balance { get; set; }
        public DbSet<SR_Student_Classes> SR_Student_Classes { get; set; }
        public DbSet<SR_Student_Logs> SR_Student_Logs { get; set; }
        public DbSet<SR_Student_MedicalCards> SR_Student_MedicalCards { get; set; }
        public DbSet<SR_Student_MedicalConditions> SR_Student_MedicalConditions { get; set; }
        public DbSet<SR_Student_MedicalInformation> SR_Student_MedicalInformation { get; set; }
        public DbSet<SR_Student_SchoolMedicalHistory> SR_Student_SchoolMedicalHistory { get; set; }
        public DbSet<SR_Student_SchoolMedicalInjuries> SR_Student_SchoolMedicalInjuries { get; set; }
        public DbSet<SR_StudentAbsenceLog> SR_StudentAbsenceLog { get; set; }
        public DbSet<SR_StudentAddressMapping> SR_StudentAddressMapping { get; set; }
        public DbSet<SR_StudentEarlyLeaveLog> SR_StudentEarlyLeaveLog { get; set; }
        public DbSet<SR_StudentGuardianMapping> SR_StudentGuardianMapping { get; set; }
        public DbSet<SR_Students> SR_Students { get; set; }
        public DbSet<ST_AddressInformation> ST_AddressInformation { get; set; }
        public DbSet<ST_GuardianInformation> ST_GuardianInformation { get; set; }
        public DbSet<ST_StudentGaurdian> ST_StudentGaurdian { get; set; }
        public DbSet<Student_ExtendedLeave> Student_ExtendedLeave { get; set; }
        public DbSet<StudentAbsentEmailLog> StudentAbsentEmailLogs { get; set; }
        public DbSet<StudentClassCode> StudentClassCodes { get; set; }
        public DbSet<StudentComment> StudentComments { get; set; }
        public DbSet<StudentLateEmailLog> StudentLateEmailLogs { get; set; }
        public DbSet<StudentVaccinationHistory> StudentVaccinationHistories { get; set; }
        public DbSet<SubjectDescription> SubjectDescriptions { get; set; }
        public DbSet<Subject> Subjects { get; set; }
        public DbSet<Supplier> Suppliers { get; set; }
        public DbSet<SYS_Attendance_Status> SYS_Attendance_Status { get; set; }
        public DbSet<SYS_Attendance_Status_Reason> SYS_Attendance_Status_Reason { get; set; }
        public DbSet<SYS_PublicHolidays> SYS_PublicHolidays { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TaskAssessmentFile> TaskAssessmentFiles { get; set; }
        public DbSet<TaskAssessment> TaskAssessments { get; set; }
        public DbSet<TeacherClassCode> TeacherClassCodes { get; set; }
        public DbSet<TeacherCrossCampus> TeacherCrossCampuses { get; set; }
        public DbSet<TermWeight> TermWeights { get; set; }
        public DbSet<TR_AccruedLeaves> TR_AccruedLeaves { get; set; }
        public DbSet<TR_AccrueRunLog> TR_AccrueRunLog { get; set; }
        public DbSet<TR_ClassTeachers> TR_ClassTeachers { get; set; }
        public DbSet<TR_EmploymentHistory> TR_EmploymentHistory { get; set; }
        public DbSet<TR_HazardRequests> TR_HazardRequests { get; set; }
        public DbSet<TR_IncursionExcursionClasses> TR_IncursionExcursionClasses { get; set; }
        public DbSet<TR_IncursionExcursionRequests> TR_IncursionExcursionRequests { get; set; }
        public DbSet<TR_ItSupportRequests> TR_ItSupportRequests { get; set; }
        public DbSet<TR_LeaveLog> TR_LeaveLog { get; set; }
        public DbSet<TR_MaintenanceRequests> TR_MaintenanceRequests { get; set; }
        public DbSet<TR_PurchaseOrderRequestLines> TR_PurchaseOrderRequestLines { get; set; }
        public DbSet<TR_PurchaseOrderRequests> TR_PurchaseOrderRequests { get; set; }
        public DbSet<TR_RequestRights> TR_RequestRights { get; set; }
        public DbSet<TR_StaffSchedule> TR_StaffSchedule { get; set; }
        public DbSet<Tr_TeacherBankingDetail> Tr_TeacherBankingDetail { get; set; }
        public DbSet<TR_Teachers> TR_Teachers { get; set; }
        public DbSet<TR_TeachersIdentification> TR_TeachersIdentification { get; set; }
        public DbSet<TR_TeachersPurchaseOrderBalance> TR_TeachersPurchaseOrderBalance { get; set; }
        public DbSet<TR_TeacherVenueHireRequestClassses> TR_TeacherVenueHireRequestClassses { get; set; }
        public DbSet<TR_TeacherVenueRequests> TR_TeacherVenueRequests { get; set; }
        public DbSet<UMS_Objects> UMS_Objects { get; set; }
        public DbSet<UMS_Permissions> UMS_Permissions { get; set; }
        public DbSet<UMS_Roles> UMS_Roles { get; set; }
        public DbSet<UMS_Users> UMS_Users { get; set; }
        public DbSet<VitWwcc> VitWwccs { get; set; }
    }
}
