//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluationType
    {
        public EvaluationType()
        {
            this.TermWeights = new HashSet<TermWeight>();
        }
    
        public int EvaluationTypeId { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<TermWeight> TermWeights { get; set; }
    }
}
