//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public Feedback()
        {
            this.Feedback_RelatedStaff = new HashSet<Feedback_RelatedStaff>();
        }
    
        public int FeedbackId { get; set; }
        public int CallerTypeId { get; set; }
        public int CallerId { get; set; }
        public int FeedbackTypeId { get; set; }
        public string Description { get; set; }
        public string Response { get; set; }
        public bool ContactBack { get; set; }
        public System.DateTime RecCreatedDate { get; set; }
        public int RecCreatedBy { get; set; }
        public System.DateTime RecLastUpdatedDate { get; set; }
        public int RecLastUpdatedBy { get; set; }
        public short StatusId { get; set; }
        public int StatusLevelId { get; set; }
    
        public virtual Config_CallerTypes Config_CallerTypes { get; set; }
        public virtual Config_FeedbackTypes Config_FeedbackTypes { get; set; }
        public virtual Config_Statuses Config_Statuses { get; set; }
        public virtual Feedback_Callers Feedback_Callers { get; set; }
        public virtual ICollection<Feedback_RelatedStaff> Feedback_RelatedStaff { get; set; }
    }
}
