//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveType
    {
        public LeaveType()
        {
            this.Att_Staff_Leaves = new HashSet<Att_Staff_Leaves>();
        }
    
        public int LeaveTypeId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Key { get; set; }
        public bool IsPaid { get; set; }
    
        public virtual ICollection<Att_Staff_Leaves> Att_Staff_Leaves { get; set; }
    }
}
