//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSG_MessageStatus
    {
        public int MessageStatusId { get; set; }
        public Nullable<System.DateTime> MessageDate { get; set; }
        public Nullable<int> MessageTypeId { get; set; }
        public Nullable<int> RollTimeStatusId { get; set; }
    }
}
