//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role_AttendanceStatus
    {
        public int Id { get; set; }
        public int RoleId { get; set; }
        public int AttendanceStatusId { get; set; }
        public Nullable<int> ReasonId { get; set; }
    }
}
