//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rpt_Incidents
    {
        public Rpt_Incidents()
        {
            this.Att_StudentReflection_Attendance = new HashSet<Att_StudentReflection_Attendance>();
            this.Rpt_IncidentParties = new HashSet<Rpt_IncidentParties>();
            this.Rpt_IncidentWitnesses = new HashSet<Rpt_IncidentWitnesses>();
        }
    
        public int IncidentId { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public short IncidentTypeId { get; set; }
        public string Description { get; set; }
        public string TeacherResponse { get; set; }
        public System.DateTime RecCreatedDate { get; set; }
        public int RecCreatedBy { get; set; }
        public int TeacherId { get; set; }
        public short StatusId { get; set; }
        public string Response { get; set; }
        public Nullable<int> ChainId { get; set; }
        public string SmsText { get; set; }
        public Nullable<bool> PublishReport { get; set; }
        public Nullable<System.DateTime> ReflectionDate { get; set; }
        public Nullable<int> ReflectionLevel { get; set; }
        public Nullable<bool> IsSuspensionEmailSent { get; set; }
    
        public virtual ICollection<Att_StudentReflection_Attendance> Att_StudentReflection_Attendance { get; set; }
        public virtual Config_IncidentType Config_IncidentType { get; set; }
        public virtual Config_Statuses Config_Statuses { get; set; }
        public virtual ICollection<Rpt_IncidentParties> Rpt_IncidentParties { get; set; }
        public virtual TR_Teachers TR_Teachers { get; set; }
        public virtual ICollection<Rpt_IncidentWitnesses> Rpt_IncidentWitnesses { get; set; }
    }
}
