//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rpt_BehaviorReports
    {
        public Rpt_BehaviorReports()
        {
            this.Rpt_BehaviorWitnesses = new HashSet<Rpt_BehaviorWitnesses>();
            this.Config_BehaviorTypes = new HashSet<Config_BehaviorTypes>();
        }
    
        public int BehaviorReportId { get; set; }
        public int StudentId { get; set; }
        public System.DateTime ReportDate { get; set; }
        public System.TimeSpan ReportTime { get; set; }
        public string ReportDescription { get; set; }
        public string TeacherResponse { get; set; }
        public int TeacherId { get; set; }
        public Nullable<int> ChainId { get; set; }
        public Nullable<int> IncidentId { get; set; }
        public short StatusId { get; set; }
        public System.DateTime RecCreatedDate { get; set; }
        public int RecLastUpdateBy { get; set; }
        public System.DateTime RecLastUpdatedDate { get; set; }
    
        public virtual Config_Statuses Config_Statuses { get; set; }
        public virtual SR_Students SR_Students { get; set; }
        public virtual TR_Teachers TR_Teachers { get; set; }
        public virtual ICollection<Rpt_BehaviorWitnesses> Rpt_BehaviorWitnesses { get; set; }
        public virtual ICollection<Config_BehaviorTypes> Config_BehaviorTypes { get; set; }
    }
}
