//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Semester
    {
        public Semester()
        {
            this.Config_Terms = new HashSet<Config_Terms>();
            this.TermWeights = new HashSet<TermWeight>();
        }
    
        public int SemesterId { get; set; }
        public string SemesterName { get; set; }
        public string SemesterCode { get; set; }
        public int Year { get; set; }
    
        public virtual ICollection<Config_Terms> Config_Terms { get; set; }
        public virtual ICollection<TermWeight> TermWeights { get; set; }
    }
}
