//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SR_Student_Logs
    {
        public int StudentLogId { get; set; }
        public System.DateTime LogDate { get; set; }
        public System.TimeSpan LogTime { get; set; }
        public int StudentId { get; set; }
        public string LogDescription { get; set; }
        public string TeacherResponse { get; set; }
        public int TeacherId { get; set; }
        public short StatusId { get; set; }
        public System.DateTime RecCreatedDate { get; set; }
        public int RecLastUpdatedBy { get; set; }
        public System.DateTime RecLastUpdatedDate { get; set; }
    
        public virtual Config_Statuses Config_Statuses { get; set; }
        public virtual SR_Students SR_Students { get; set; }
        public virtual TR_Teachers TR_Teachers { get; set; }
    }
}
