//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SR_Student_SchoolMedicalInjuries
    {
        public int MedicalHistoryId { get; set; }
        public int InjuryTypeId { get; set; }
    
        public virtual SR_Student_SchoolMedicalHistory SR_Student_SchoolMedicalHistory { get; set; }
    }
}
