//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SR_Student_MedicalInformation
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public string MedicalComments { get; set; }
        public Nullable<System.DateTime> DateLastTetanus { get; set; }
        public bool SharingFlag { get; set; }
        public string DoctorName { get; set; }
        public string DoctorContact { get; set; }
        public string MedicalAlert { get; set; }
    }
}
