//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SR_Student_SchoolMedicalHistory
    {
        public SR_Student_SchoolMedicalHistory()
        {
            this.SR_Student_SchoolMedicalInjuries = new HashSet<SR_Student_SchoolMedicalInjuries>();
        }
    
        public int MedicalHistoryId { get; set; }
        public int StudentId { get; set; }
        public System.DateTime IncidentDate { get; set; }
        public string Treatment { get; set; }
        public Nullable<System.TimeSpan> TimeIn { get; set; }
        public Nullable<int> IncidentLocation { get; set; }
        public Nullable<System.TimeSpan> TimeOut { get; set; }
        public Nullable<int> Disposition { get; set; }
        public System.DateTime RecCreatedDate { get; set; }
        public System.DateTime RecLastUpdatedDate { get; set; }
        public int RecCreatedBy { get; set; }
        public int RecLastUpdatedBy { get; set; }
    
        public virtual Config_Room Config_Room { get; set; }
        public virtual Config_Room Config_Room1 { get; set; }
        public virtual ICollection<SR_Student_SchoolMedicalInjuries> SR_Student_SchoolMedicalInjuries { get; set; }
    }
}
