//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SR_Students
    {
        public SR_Students()
        {
            this.Att_StudentReflection_Attendance = new HashSet<Att_StudentReflection_Attendance>();
            this.Config_StudentWorkHabit = new HashSet<Config_StudentWorkHabit>();
            this.Config_SubjectWorkHabits = new HashSet<Config_SubjectWorkHabits>();
            this.Grades = new HashSet<Grade>();
            this.Rpt_BehaviorReports = new HashSet<Rpt_BehaviorReports>();
            this.Rpt_IncidentParties = new HashSet<Rpt_IncidentParties>();
            this.Rpt_IncidentWitnesses = new HashSet<Rpt_IncidentWitnesses>();
            this.SR_Student_Balance = new HashSet<SR_Student_Balance>();
            this.SR_Student_Classes = new HashSet<SR_Student_Classes>();
            this.SR_Student_Logs = new HashSet<SR_Student_Logs>();
            this.SR_StudentAddressMapping = new HashSet<SR_StudentAddressMapping>();
            this.SR_StudentGuardianMapping = new HashSet<SR_StudentGuardianMapping>();
            this.StudentClassCodes = new HashSet<StudentClassCode>();
            this.StudentVaccinationHistories = new HashSet<StudentVaccinationHistory>();
            this.TR_IncursionExcursionClasses = new HashSet<TR_IncursionExcursionClasses>();
        }
    
        public int StudentId { get; set; }
        public string RegistrationNo { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
        public string SmallPicture { get; set; }
        public string LargePicture { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED_DATE { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<int> LAST_MODIFIED_BY { get; set; }
        public Nullable<int> VERSION_NUMBER { get; set; }
        public string Gender { get; set; }
        public Nullable<int> CampusId { get; set; }
        public string Indigenous { get; set; }
        public Nullable<System.DateTime> EnrolmentDate { get; set; }
        public Nullable<System.DateTime> TerminationDate { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Nationality { get; set; }
        public string PlaceOfBirth { get; set; }
    
        public virtual ICollection<Att_StudentReflection_Attendance> Att_StudentReflection_Attendance { get; set; }
        public virtual Config_Campus Config_Campus { get; set; }
        public virtual ICollection<Config_StudentWorkHabit> Config_StudentWorkHabit { get; set; }
        public virtual ICollection<Config_SubjectWorkHabits> Config_SubjectWorkHabits { get; set; }
        public virtual ICollection<Grade> Grades { get; set; }
        public virtual ICollection<Rpt_BehaviorReports> Rpt_BehaviorReports { get; set; }
        public virtual ICollection<Rpt_IncidentParties> Rpt_IncidentParties { get; set; }
        public virtual ICollection<Rpt_IncidentWitnesses> Rpt_IncidentWitnesses { get; set; }
        public virtual ICollection<SR_Student_Balance> SR_Student_Balance { get; set; }
        public virtual ICollection<SR_Student_Classes> SR_Student_Classes { get; set; }
        public virtual ICollection<SR_Student_Logs> SR_Student_Logs { get; set; }
        public virtual ICollection<SR_StudentAddressMapping> SR_StudentAddressMapping { get; set; }
        public virtual ICollection<SR_StudentGuardianMapping> SR_StudentGuardianMapping { get; set; }
        public virtual ICollection<StudentClassCode> StudentClassCodes { get; set; }
        public virtual ICollection<StudentVaccinationHistory> StudentVaccinationHistories { get; set; }
        public virtual ICollection<TR_IncursionExcursionClasses> TR_IncursionExcursionClasses { get; set; }
    }
}
