//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SR_Student_MedicalConditions
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public int MedicalConditionTypeId { get; set; }
    
        public virtual Config_MedicalConditionTypes Config_MedicalConditionTypes { get; set; }
    }
}
