//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_AddressInformation
    {
        public ST_AddressInformation()
        {
            this.SR_StudentAddressMapping = new HashSet<SR_StudentAddressMapping>();
        }
    
        public int AddressInformationId { get; set; }
        public int AddressTypeId { get; set; }
        public string Address { get; set; }
        public string Subrub { get; set; }
        public string State { get; set; }
        public string PostCode { get; set; }
    
        public virtual Config_AddressType Config_AddressType { get; set; }
        public virtual ICollection<SR_StudentAddressMapping> SR_StudentAddressMapping { get; set; }
    }
}
