//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_GuardianInformation
    {
        public ST_GuardianInformation()
        {
            this.ParentPortalLogs = new HashSet<ParentPortalLog>();
            this.SR_StudentGuardianMapping = new HashSet<SR_StudentGuardianMapping>();
        }
    
        public int GuardianInformationId { get; set; }
        public int GuardianTypeId { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public string HomePhone { get; set; }
        public string BusinessPhone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string PinCode { get; set; }
    
        public virtual Config_GuardianType Config_GuardianType { get; set; }
        public virtual ICollection<ParentPortalLog> ParentPortalLogs { get; set; }
        public virtual ICollection<SR_StudentGuardianMapping> SR_StudentGuardianMapping { get; set; }
    }
}
