//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_StudentGaurdian
    {
        public int StudentGaurdianId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public string Name { get; set; }
        public string Relation { get; set; }
        public string EmailId { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<int> HomePhone { get; set; }
    }
}
