//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_ExtendedLeave
    {
        public int StudentExtendedLeaveId { get; set; }
        public int StudentClassId { get; set; }
        public int AttendanceStatusId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual SR_Student_Classes SR_Student_Classes { get; set; }
    }
}
