//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentVaccinationHistory
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public int VaccinationTypeId { get; set; }
        public int VaccinationAgeId { get; set; }
    
        public virtual Config_VaccinationAgeTypes Config_VaccinationAgeTypes { get; set; }
        public virtual Config_VaccinationTypes Config_VaccinationTypes { get; set; }
        public virtual SR_Students SR_Students { get; set; }
    }
}
