//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public Subject()
        {
            this.AssessmentLinks = new HashSet<AssessmentLink>();
            this.ClassCodes = new HashSet<ClassCode>();
            this.Config_DomainBalance = new HashSet<Config_DomainBalance>();
            this.Config_Task = new HashSet<Config_Task>();
            this.PreApprovedSubjects = new HashSet<PreApprovedSubject>();
            this.TR_PurchaseOrderRequests = new HashSet<TR_PurchaseOrderRequests>();
            this.TermWeights = new HashSet<TermWeight>();
        }
    
        public int SubjectId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> SubjectOrder { get; set; }
    
        public virtual ICollection<AssessmentLink> AssessmentLinks { get; set; }
        public virtual ICollection<ClassCode> ClassCodes { get; set; }
        public virtual ICollection<Config_DomainBalance> Config_DomainBalance { get; set; }
        public virtual ICollection<Config_Task> Config_Task { get; set; }
        public virtual ICollection<PreApprovedSubject> PreApprovedSubjects { get; set; }
        public virtual ICollection<TR_PurchaseOrderRequests> TR_PurchaseOrderRequests { get; set; }
        public virtual ICollection<TermWeight> TermWeights { get; set; }
    }
}
