//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Attendance_Status_Reason
    {
        public SYS_Attendance_Status_Reason()
        {
            this.ATT_Staff_Attendance = new HashSet<ATT_Staff_Attendance>();
        }
    
        public int ReasonId { get; set; }
        public string ReasonName { get; set; }
        public int AttendanceStatusId { get; set; }
        public string AttendanceSymbol { get; set; }
        public Nullable<int> SortPosition { get; set; }
        public Nullable<int> ReasonKey { get; set; }
        public Nullable<bool> ShowInMenu { get; set; }
    
        public virtual ICollection<ATT_Staff_Attendance> ATT_Staff_Attendance { get; set; }
        public virtual SYS_Attendance_Status SYS_Attendance_Status { get; set; }
    }
}
