//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_PublicHolidays
    {
        public int HolidayId { get; set; }
        public string HolidayName { get; set; }
        public Nullable<System.DateTime> StartDateHoliday { get; set; }
        public Nullable<System.DateTime> EndDateHoliday { get; set; }
        public Nullable<int> CampusId { get; set; }
    }
}
