//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Attendance_Status
    {
        public SYS_Attendance_Status()
        {
            this.ATT_Staff_Attendance = new HashSet<ATT_Staff_Attendance>();
            this.Notification_Configuration = new HashSet<Notification_Configuration>();
            this.SYS_Attendance_Status_Reason = new HashSet<SYS_Attendance_Status_Reason>();
        }
    
        public int AttendanceStatusId { get; set; }
        public string Name { get; set; }
        public int CategoryType { get; set; }
        public Nullable<int> SortPosition { get; set; }
        public string OrderNo { get; set; }
        public string AttendanceSymbol { get; set; }
        public string CssClass { get; set; }
        public string DisplayName { get; set; }
        public Nullable<bool> ShowInStaffApp { get; set; }
    
        public virtual ICollection<ATT_Staff_Attendance> ATT_Staff_Attendance { get; set; }
        public virtual ICollection<Notification_Configuration> Notification_Configuration { get; set; }
        public virtual ICollection<SYS_Attendance_Status_Reason> SYS_Attendance_Status_Reason { get; set; }
    }
}
