//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskAssessment
    {
        public TaskAssessment()
        {
            this.Grades = new HashSet<Grade>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> TotalMarks { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> ClassCodeId { get; set; }
        public Nullable<int> TaskTypeId { get; set; }
        public Nullable<int> AssessmentId { get; set; }
        public Nullable<int> TermId { get; set; }
        public string ShortName { get; set; }
        public string DetailedDescription { get; set; }
        public string FileName { get; set; }
    
        public virtual AssessmentLink AssessmentLink { get; set; }
        public virtual ClassCode ClassCode { get; set; }
        public virtual Config_Task Config_Task { get; set; }
        public virtual ICollection<Grade> Grades { get; set; }
    }
}
