//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TermWeight
    {
        public int Id { get; set; }
        public Nullable<int> TermId { get; set; }
        public int EvaluationTypeId { get; set; }
        public int SubjectId { get; set; }
        public int SemesterId { get; set; }
        public int ClassId { get; set; }
        public int CampusId { get; set; }
        public int Weight { get; set; }
    
        public virtual Config_Terms Config_Terms { get; set; }
        public virtual EvaluationType EvaluationType { get; set; }
        public virtual Semester Semester { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
