//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_AccruedLeaves
    {
        public int TeacherAccruedLeaveId { get; set; }
        public double Balance { get; set; }
        public int Year { get; set; }
        public int TeacherId { get; set; }
        public Nullable<System.DateTime> RecLastUpdatedDt { get; set; }
        public Nullable<double> Deductions { get; set; }
    }
}
