//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_ClassTeachers
    {
        public TR_ClassTeachers()
        {
            this.Att_Staff_ExemptedPeriods = new HashSet<Att_Staff_ExemptedPeriods>();
            this.Att_Staff_HomeroomReplacements = new HashSet<Att_Staff_HomeroomReplacements>();
        }
    
        public int ClassTeacherId { get; set; }
        public Nullable<int> TeacherId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> SectionId { get; set; }
        public Nullable<bool> IsIncharge { get; set; }
        public Nullable<int> TermId { get; set; }
        public Nullable<bool> ShowStudents { get; set; }
    
        public virtual ICollection<Att_Staff_ExemptedPeriods> Att_Staff_ExemptedPeriods { get; set; }
        public virtual ICollection<Att_Staff_HomeroomReplacements> Att_Staff_HomeroomReplacements { get; set; }
        public virtual Config_Class Config_Class { get; set; }
        public virtual Config_Section Config_Section { get; set; }
        public virtual TR_Teachers TR_Teachers { get; set; }
    }
}
