//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_EmploymentHistory
    {
        public int EmploymentHistoryId { get; set; }
        public int TeacherId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> TerminationDate { get; set; }
        public int CategoryId { get; set; }
        public int CampusId { get; set; }
        public int WorkLoadId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Config_Campus Config_Campus { get; set; }
        public virtual Config_StaffCategory Config_StaffCategory { get; set; }
        public virtual Config_StaffWorkLoad Config_StaffWorkLoad { get; set; }
        public virtual TR_Teachers TR_Teachers { get; set; }
    }
}
