//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_ItSupportRequests
    {
        public int ItSupportRequestId { get; set; }
        public int ItSupportTypeId { get; set; }
        public string Location { get; set; }
        public string Description { get; set; }
        public short StatusId { get; set; }
        public int TeacherId { get; set; }
        public System.DateTime RecCreatedDate { get; set; }
        public int RecCreatedBy { get; set; }
        public System.DateTime RecLastUpdatedDate { get; set; }
        public int RecLastUpdatedBy { get; set; }
        public string Response { get; set; }
        public int CampusId { get; set; }
    
        public virtual Config_Campus Config_Campus { get; set; }
        public virtual Config_ItSupportTypes Config_ItSupportTypes { get; set; }
        public virtual Config_Statuses Config_Statuses { get; set; }
        public virtual TR_Teachers TR_Teachers { get; set; }
    }
}
