//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_IncursionExcursionClasses
    {
        public int IncursionExcursionClassId { get; set; }
        public int RequestId { get; set; }
        public int ClassId { get; set; }
        public int SectionId { get; set; }
        public Nullable<int> TeacherClassCodeId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsBalanceDeducted { get; set; }
    
        public virtual Config_Class Config_Class { get; set; }
        public virtual Config_Section Config_Section { get; set; }
        public virtual SR_Students SR_Students { get; set; }
        public virtual TeacherClassCode TeacherClassCode { get; set; }
        public virtual TR_IncursionExcursionRequests TR_IncursionExcursionRequests { get; set; }
    }
}
