//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_LeaveLog
    {
        public long LeaveLogId { get; set; }
        public int TeacherId { get; set; }
        public Nullable<int> LeaveId { get; set; }
        public double BalanceBefore { get; set; }
        public double BalanceAfter { get; set; }
        public System.DateTime RecCreatedDate { get; set; }
    
        public virtual Att_Staff_Leaves Att_Staff_Leaves { get; set; }
        public virtual TR_Teachers TR_Teachers { get; set; }
    }
}
