//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_StaffSchedule
    {
        public long ScheduleId { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> FinishTime { get; set; }
        public Nullable<System.DateTime> FirstDay { get; set; }
        public Nullable<System.DateTime> LastDay { get; set; }
        public System.DateTime RecCreatedDt { get; set; }
        public string RecCreatedBy { get; set; }
        public System.DateTime RecLastUpdateDate { get; set; }
        public string RecLastUpdatedBy { get; set; }
        public int TeacherId { get; set; }
        public int BreakId { get; set; }
        public int DayId { get; set; }
        public Nullable<int> CampusId { get; set; }
    
        public virtual Config_StaffBreak Config_StaffBreak { get; set; }
        public virtual Config_StaffWorkDays Config_StaffWorkDays { get; set; }
        public virtual TR_Teachers TR_Teachers { get; set; }
    }
}
