//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_TeachersPurchaseOrderBalance
    {
        public int TeacherBalanceId { get; set; }
        public int TeacherId { get; set; }
        public decimal Balance { get; set; }
        public string BalanceYear { get; set; }
    
        public virtual TR_Teachers TR_Teachers { get; set; }
    }
}
