//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_TeacherVenueRequests
    {
        public TR_TeacherVenueRequests()
        {
            this.TR_TeacherVenueHireRequestClassses = new HashSet<TR_TeacherVenueHireRequestClassses>();
        }
    
        public int VenueHireRequestId { get; set; }
        public string Venue { get; set; }
        public string Purpose { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public string AdditionalInformation { get; set; }
        public short StatusId { get; set; }
        public int Attendance { get; set; }
        public int TeacherId { get; set; }
        public System.DateTime ReCreatedDate { get; set; }
        public int RecCreatedBy { get; set; }
        public System.DateTime RecLastUpdatedDate { get; set; }
        public int RecLastUpdatedBy { get; set; }
        public string Classes { get; set; }
        public string Response { get; set; }
        public string StaffAttending { get; set; }
        public Nullable<int> CampusId { get; set; }
        public Nullable<int> VenueHireTypeId { get; set; }
    
        public virtual Config_Statuses Config_Statuses { get; set; }
        public virtual Config_VenueHire_Types Config_VenueHire_Types { get; set; }
        public virtual TR_Teachers TR_Teachers { get; set; }
        public virtual ICollection<TR_TeacherVenueHireRequestClassses> TR_TeacherVenueHireRequestClassses { get; set; }
    }
}
