//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_Teachers
    {
        public TR_Teachers()
        {
            this.Allotments_TeacherSalaries = new HashSet<Allotments_TeacherSalaries>();
            this.Att_Staff_AdvanceReplacements = new HashSet<Att_Staff_AdvanceReplacements>();
            this.Att_Staff_AdvanceReplacements1 = new HashSet<Att_Staff_AdvanceReplacements>();
            this.ATT_Staff_Attendance = new HashSet<ATT_Staff_Attendance>();
            this.Att_Staff_ExemptedPeriods = new HashSet<Att_Staff_ExemptedPeriods>();
            this.Att_Staff_HomeroomReplacements = new HashSet<Att_Staff_HomeroomReplacements>();
            this.Att_Staff_InServiceRequests = new HashSet<Att_Staff_InServiceRequests>();
            this.Att_Staff_Leaves = new HashSet<Att_Staff_Leaves>();
            this.Att_Staff_Replacements = new HashSet<Att_Staff_Replacements>();
            this.Att_Staff_Replacements1 = new HashSet<Att_Staff_Replacements>();
            this.Config_Leadership_Team = new HashSet<Config_Leadership_Team>();
            this.Config_StudentWorkHabit = new HashSet<Config_StudentWorkHabit>();
            this.Feedback_RelatedStaff = new HashSet<Feedback_RelatedStaff>();
            this.Msg_TeacherAssociation = new HashSet<Msg_TeacherAssociation>();
            this.Rpt_BehaviorReports = new HashSet<Rpt_BehaviorReports>();
            this.Rpt_Incidents = new HashSet<Rpt_Incidents>();
            this.Rpt_IncidentWitnesses = new HashSet<Rpt_IncidentWitnesses>();
            this.SR_Student_Logs = new HashSet<SR_Student_Logs>();
            this.TeacherClassCodes = new HashSet<TeacherClassCode>();
            this.TeacherCrossCampuses = new HashSet<TeacherCrossCampus>();
            this.TR_ClassTeachers = new HashSet<TR_ClassTeachers>();
            this.TR_EmploymentHistory = new HashSet<TR_EmploymentHistory>();
            this.TR_HazardRequests = new HashSet<TR_HazardRequests>();
            this.TR_IncursionExcursionRequests = new HashSet<TR_IncursionExcursionRequests>();
            this.TR_ItSupportRequests = new HashSet<TR_ItSupportRequests>();
            this.TR_LeaveLog = new HashSet<TR_LeaveLog>();
            this.TR_MaintenanceRequests = new HashSet<TR_MaintenanceRequests>();
            this.TR_PurchaseOrderRequests = new HashSet<TR_PurchaseOrderRequests>();
            this.TR_RequestRights = new HashSet<TR_RequestRights>();
            this.TR_StaffSchedule = new HashSet<TR_StaffSchedule>();
            this.Tr_TeacherBankingDetail = new HashSet<Tr_TeacherBankingDetail>();
            this.TR_TeachersPurchaseOrderBalance = new HashSet<TR_TeachersPurchaseOrderBalance>();
            this.TR_TeachersIdentification = new HashSet<TR_TeachersIdentification>();
            this.TR_TeacherVenueRequests = new HashSet<TR_TeacherVenueRequests>();
            this.TR_IncursionExcursionRequests1 = new HashSet<TR_IncursionExcursionRequests>();
        }
    
        public int TeacherId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string MobileNumber { get; set; }
        public string VIT { get; set; }
        public string WWCC { get; set; }
        public Nullable<int> CampusId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> RecCreatedDt { get; set; }
        public string RecCreatedBy { get; set; }
        public Nullable<System.DateTime> RecLastUpdateDate { get; set; }
        public string RecLastUpdatedBy { get; set; }
        public Nullable<int> WorkLoadId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string BirthPlace { get; set; }
        public string Gender { get; set; }
        public string HomeAddress { get; set; }
        public string Subrub { get; set; }
        public string State { get; set; }
        public string HomePhone { get; set; }
        public string PostCode { get; set; }
        public string Position { get; set; }
        public string NextOfKin { get; set; }
        public string NoKPhone { get; set; }
        public Nullable<int> EmploymentType { get; set; }
        public string Initials { get; set; }
        public string Title { get; set; }
        public string TeacherGuid { get; set; }
    
        public virtual ICollection<Allotments_TeacherSalaries> Allotments_TeacherSalaries { get; set; }
        public virtual ICollection<Att_Staff_AdvanceReplacements> Att_Staff_AdvanceReplacements { get; set; }
        public virtual ICollection<Att_Staff_AdvanceReplacements> Att_Staff_AdvanceReplacements1 { get; set; }
        public virtual ICollection<ATT_Staff_Attendance> ATT_Staff_Attendance { get; set; }
        public virtual ICollection<Att_Staff_ExemptedPeriods> Att_Staff_ExemptedPeriods { get; set; }
        public virtual ICollection<Att_Staff_HomeroomReplacements> Att_Staff_HomeroomReplacements { get; set; }
        public virtual ICollection<Att_Staff_InServiceRequests> Att_Staff_InServiceRequests { get; set; }
        public virtual ICollection<Att_Staff_Leaves> Att_Staff_Leaves { get; set; }
        public virtual ICollection<Att_Staff_Replacements> Att_Staff_Replacements { get; set; }
        public virtual ICollection<Att_Staff_Replacements> Att_Staff_Replacements1 { get; set; }
        public virtual ICollection<Config_Leadership_Team> Config_Leadership_Team { get; set; }
        public virtual ICollection<Config_StudentWorkHabit> Config_StudentWorkHabit { get; set; }
        public virtual ICollection<Feedback_RelatedStaff> Feedback_RelatedStaff { get; set; }
        public virtual ICollection<Msg_TeacherAssociation> Msg_TeacherAssociation { get; set; }
        public virtual ICollection<Rpt_BehaviorReports> Rpt_BehaviorReports { get; set; }
        public virtual ICollection<Rpt_Incidents> Rpt_Incidents { get; set; }
        public virtual ICollection<Rpt_IncidentWitnesses> Rpt_IncidentWitnesses { get; set; }
        public virtual ICollection<SR_Student_Logs> SR_Student_Logs { get; set; }
        public virtual ICollection<TeacherClassCode> TeacherClassCodes { get; set; }
        public virtual ICollection<TeacherCrossCampus> TeacherCrossCampuses { get; set; }
        public virtual ICollection<TR_ClassTeachers> TR_ClassTeachers { get; set; }
        public virtual ICollection<TR_EmploymentHistory> TR_EmploymentHistory { get; set; }
        public virtual ICollection<TR_HazardRequests> TR_HazardRequests { get; set; }
        public virtual ICollection<TR_IncursionExcursionRequests> TR_IncursionExcursionRequests { get; set; }
        public virtual ICollection<TR_ItSupportRequests> TR_ItSupportRequests { get; set; }
        public virtual ICollection<TR_LeaveLog> TR_LeaveLog { get; set; }
        public virtual ICollection<TR_MaintenanceRequests> TR_MaintenanceRequests { get; set; }
        public virtual ICollection<TR_PurchaseOrderRequests> TR_PurchaseOrderRequests { get; set; }
        public virtual ICollection<TR_RequestRights> TR_RequestRights { get; set; }
        public virtual ICollection<TR_StaffSchedule> TR_StaffSchedule { get; set; }
        public virtual ICollection<Tr_TeacherBankingDetail> Tr_TeacherBankingDetail { get; set; }
        public virtual ICollection<TR_TeachersPurchaseOrderBalance> TR_TeachersPurchaseOrderBalance { get; set; }
        public virtual ICollection<TR_TeachersIdentification> TR_TeachersIdentification { get; set; }
        public virtual ICollection<TR_TeacherVenueRequests> TR_TeacherVenueRequests { get; set; }
        public virtual ICollection<TR_IncursionExcursionRequests> TR_IncursionExcursionRequests1 { get; set; }
    }
}
