//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tr_TeacherBankingDetail
    {
        public int TeacherBankingDetailId { get; set; }
        public int TeacherId { get; set; }
        public string BankName { get; set; }
        public string BankAddress { get; set; }
        public string NameOfAccount { get; set; }
        public string BSBNo { get; set; }
        public string AccountNo { get; set; }
        public Nullable<System.DateTime> RecCreatedDate { get; set; }
        public Nullable<System.DateTime> RecLastUpdateDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual TR_Teachers TR_Teachers { get; set; }
    }
}
