//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_TeachersIdentification
    {
        public int TeachersIdentificationId { get; set; }
        public int TeacherId { get; set; }
        public int IdentificationTypeId { get; set; }
        public string IdentificationNumber { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public string ImagePath { get; set; }
        public bool IsConfirmed { get; set; }
        public System.DateTime RecLastUpdateDate { get; set; }
        public Nullable<System.DateTime> ConfirmationDate { get; set; }
    
        public virtual TR_Teachers TR_Teachers { get; set; }
    }
}
