//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_TeacherVenueHireRequestClassses
    {
        public int VenueHireRequestClassId { get; set; }
        public int ClassId { get; set; }
        public int VenueHireRequestId { get; set; }
        public int SectionId { get; set; }
    
        public virtual Config_Class Config_Class { get; set; }
        public virtual Config_Section Config_Section { get; set; }
        public virtual TR_TeacherVenueRequests TR_TeacherVenueRequests { get; set; }
    }
}
