//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UMS_Objects
    {
        public int ObjectId { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> DeviceId { get; set; }
    }
}
