//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UMS_Permissions
    {
        public int PermissionId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> ObjectId { get; set; }
        public Nullable<bool> AddRight { get; set; }
        public Nullable<bool> EditRight { get; set; }
        public Nullable<bool> DeleteRight { get; set; }
        public Nullable<bool> ViewRight { get; set; }
    }
}
